var numero = Number(prompt("ingrese un numero"))
var numero2 = Number(prompt("Ingrese otro numero"))
alert("La multiplicación de los dos números es "+( numero * numero2 ))
alert("La resta de los dos números es " + (numero - numero2 ))
alert("La división de los dos números es "+(numero / numero2))
alert("La suma de os dos números es " +(numero+numero2))
